permissions:
  contents: read
  packages: write

name: UI CI/CD - Prod

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL_PROD }}
          VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL_PROD }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL_PROD }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}

  push_to_registry:
    needs: build
    runs-on: ubuntu-latest

    env:
      ORG_NAME: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set lowercase org and repo
        run: |
          ORG=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')
          echo "ORG_NAME=$ORG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO" >> $GITHUB_ENV

      - name: Set up Docker Buildx (multi-platform / builder)
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL_PROD }}
            VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL_PROD }}
            VITE_WS_URL=${{ secrets.VITE_WS_URL_PROD }}
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
          tags: |
            ghcr.io/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}:prod-latest
            ghcr.io/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}:prod-${{ github.sha }}

  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST_PROD }}
          username: ${{ secrets.VM_USER_PROD }}
          key: ${{ secrets.VM_SSH_KEY_PROD }}
          script: |
            cd ~/infrastructure
            ./deploy.prod.sh